### ISSUE TITLE
Updated brazilian-portuguese translation

### ISSUE THREAD

**Issue by almircanella** [developersu/ns-usbloader#32]
https://pastebin.com/EdSYRBSw

**Comment by developersu** [comment]
Thank you! you're awesome man! Will add these updates soon.

Just to clarify: If you like to add pull request (PR) it's fine and welcome. If I rejected some PRs in the past it's not because I don't want to add you as contributor but because I don't have enough skill/knowledge in GIT. I'm trying to learn it and I really appreciate the work you're doing. I know things like this matters. Anyway, thank you!

**Comment by developersu** [comment]
BTW, how to translate "Use old GoldLeaf" or "Use old GoldLeaf version"? 
I have some ideas for GLv0.5 users..
