### ISSUE TITLE
V4.0 Crashes (Windows 10 Pro)

### ISSUE THREAD

**Issue by EXO5KELETON** [developersu/ns-usbloader#65]
V4 legacy and normal seem to crash as soon as you hit select files in the games tab to upload NSP's.

Have tried two different machines on windows 10 with different ports USB 2 and USB 3 and different cables the NS-USBLOADER just crashes soon as you hit select files and stops responding.

V3 was ok.

Any help/ideas

**Comment by developersu** [comment]
@EXO5KELETON run it from terminal like 'java -jar C:\path\to\jar\file.jar' and drop me stacktrace (if it's there). 
Also I'd need your windows 10 release/version. And JDK/JRE version. And steps to reproduce. And application logs if there are any.

I tested it on Windows 10 1607 and I don't see any issues, so that's why I need more information from your side.

Thanks!

**Comment by EXO5KELETON** [comment]
It's the latest build of windows 10 v2004 and jdk14.0.1 I believe.

I'm away from the machine now until Monday

**Comment by developersu** [comment]
Yeah, it's fine. No rush with this.

**Comment by EXO5KELETON** [comment]
Quick update whatever v4 contained seems to mess up windows 10 latest build v2004 pretty badly. I've got a clean install of windows 10 with JDK14 and after I run v4 windows goes mad.. 

if I reboot the machine I can no longer do normal windows tasks like launch recycle bin launch windows defrag utility or launch system cleanup I have to literally rebuild W10.

Strange. 

I'll help you out as much as I can so let me know what you need.

Thanks

**Comment by Masamune3210** [comment]
It's likely a issue more with Java or the new update to Windows than it does this program, and considering Windows's track record, I'd wager its more that than anything else. Just was allowed finally to update to the new version today and it broke Run as Admin and context menus simply due to one misbehaving context menu item...

**Comment by developersu** [comment]
Yeah.. Just executed it on Win10 2004 with OpenJDK-14.0.2 and it works. 
Runtime:
```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```
Anyway, I agree with Masamune3210. It looks like a Java's VM issue. Try either JRE8 or JDK11. With JRE8 I didn't have any issues while using it on windows and JDK11 is LTS and I use on linux and building app with it.

As for the differences inside application between v3 and v4: new version contains 'Apache Commons CLI' embedded inside, however this part of application [does not even initialize](https://github.com/developersu/ns-usbloader/blob/5838fe3b8980bb9297a1aa28a74ddb3c744a6961/src/main/java/nsusbloader/NSLMain.java#L83-L86) inside app when you executing application as-usual: double-click or without options. That's why I'm not sure that it's because of update.

**Comment by EXO5KELETON** [comment]
Cool I'll update my JDK to v14.0.2

**Comment by EXO5KELETON** [comment]
Looks like it was a java issue.. reinstalled windows 10 and installed JRE8 and all ok. 

Thanks a lot for your help

**Comment by developersu** [comment]
You're welcome =)
