### ISSUE TITLE
Network Install Progress Bar

### ISSUE THREAD

**Issue by Buzbee** [developersu/ns-usbloader#7]
Network install works (albeit slow 0.14-0.18MB/s over wifi) on 7.01 but the progress bar does not work. Also, ns-usbloader never receives the ack that the file is complete so I must hit interrupt after tinfoil prompts to hit B after file completes. The tinfoil I'm using is located at https://github.com/fourminute/Fluffy/blob/master/Tinfoil.nro

It's description is labelled as "Latest TinFoil with USB 5.X Fix." Is another version of tinfoil recommended?

**Comment by developersu** [comment]
> 0.14-0.18MB/s over wifi

Same for me. Will think what could be done with this (most likely nothing, but need some investigation first).

>the progress bar does not work

It's normal for NET install. Without adding extra-functionality to track progress it works faster (I understand that it's dead slow).

>ns-usbloader never receives the ack that the file is complete

That's why this app can't understand when it should stop listening for connections (be interrupted). Therefore you have to hit 'Interrupt' by yourself. No idea how to make it better.

>Is another version of tinfoil recommended

Any TinFoil build should be working, with or without bugs/fixes. You're should be good with it.

Thanks!

**Comment by developersu** [comment]
Ok. Checked with nginx. Low speed it a bug. Will fix in next release. 
Thanks!

**Comment by developersu** [comment]
> 0.14-0.18MB/s over wifi
Fixed @ v0.3.2

> the progress bar does not work
Fixed @ v0.3.2

> ns-usbloader never receives the ack that the file is complete
Won't be fixed (no idea how).
